update workflow test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -178,7 +178,7 @@ jobs:
 
 
 
-  build:
+  build-and-test:
     needs: validation-and-lint
     if: ${{ inputs.run_build }}
     runs-on: ubuntu-latest
@@ -187,100 +187,113 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: ${{ inputs.java_version }}
           cache: maven
-      - name: Cache Maven repository
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-              ${{ runner.os }}-m2-
-      - name: Run build (skip tests)
-        id: run-build
+#      - name: Cache Maven repository
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#              ${{ runner.os }}-m2-
+      - name: Run build and Tests
+        if: inputs.run_build && inputs.run_unit_test
+#        id: run-build
         run: |
-          set -o pipefail
-          echo "Executing: mvn clean package -DskipTests"
-          mvn clean package -DskipTests
-            EXIT_CODE=$?
-            if [ $EXIT_CODE -eq 0 ]; then
-              echo "build_status=success" >> $GITHUB_OUTPUT
-            else
-              echo "build_status=failure" >> $GITHUB_OUTPUT
-              exit $EXIT_CODE
-            fi
-      - name: Set job output
-        id: set-output
+          mvn -B verify
+#          set -o pipefail
+#          echo "Executing: mvn clean package -DskipTests"
+#          mvn clean package -DskipTests
+#            EXIT_CODE=$?
+#            if [ $EXIT_CODE -eq 0 ]; then
+#              echo "build_status=success" >> $GITHUB_OUTPUT
+#            else
+#              echo "build_status=failure" >> $GITHUB_OUTPUT
+#              exit $EXIT_CODE
+#            fi
+      - name: Build whithout Tests
+        if: inputs.run_build && !inputs.run_unit_test
         run: |
-          # output already written to GITHUB_OUTPUT by step above; ensure it's present
-          echo "build_status=${{ steps.run-build.outputs.build_status || 'success' }}" >> $GITHUB_OUTPUT
-
-  unit_test:
-    if: ${{ inputs.run_unit_test }}
-    runs-on: ubuntu-latest
-    needs: [ validation-and-lint, build]
-    outputs:
-      test_status: ${{ steps.set-output.outputs.test_status }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: temurin
-          java-version: ${{ inputs.java_version }}
-          cache: maven
-
-      - name: Cache Maven repository
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-m2-
-
-      - name: Run tests
-        id: run-tests
-        run: |
-          set -o pipefail
-          echo "Executing: mvn test"
-          mvn test
-          EXIT_CODE=$?
-          if [ $EXIT_CODE -eq 0 ]; then
-            echo "test_status=success" >> $GITHUB_OUTPUT
-          else
-            echo "test_status=failure" >> $GITHUB_OUTPUT
-            exit $EXIT_CODE
-          fi
-
-      - name: Set job output
-        id: set-output
-        run: |
-          echo "test_status=${{ steps.run-unit_test.outputs.test_status || 'success' }}" >> $GITHUB_OUTPUT
+          mvn -B package -DskipTests
+#      - name: Set job output
+#        id: set-output
+#        run: |
+#          # output already written to GITHUB_OUTPUT by step above; ensure it's present
+#          echo "build_status=${{ steps.run-build.outputs.build_status || 'success' }}" >> $GITHUB_OUTPUT
+#
+#  unit_test:
+#    if: ${{ inputs.run_unit_test }}
+#    runs-on: ubuntu-latest
+#    needs: [ validation-and-lint, build]
+#    outputs:
+#      test_status: ${{ steps.set-output.outputs.test_status }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Setup Java
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: temurin
+#          java-version: ${{ inputs.java_version }}
+#          cache: maven
+#
+#      - name: Cache Maven repository
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-m2-
+#
+#      - name: Run tests
+#        id: run-tests
+#        run: |
+#          set -o pipefail
+#          echo "Executing: mvn test"
+#          mvn test
+#          EXIT_CODE=$?
+#          if [ $EXIT_CODE -eq 0 ]; then
+#            echo "test_status=success" >> $GITHUB_OUTPUT
+#          else
+#            echo "test_status=failure" >> $GITHUB_OUTPUT
+#            exit $EXIT_CODE
+#          fi
+#
+#      - name: Set job output
+#        id: set-output
+#        run: |
+#          echo "test_status=${{ steps.run-unit_test.outputs.test_status || 'success' }}" >> $GITHUB_OUTPUT
 
       - name: Gerar relatório Jacoco
+        if: inputs.run_unit_test
         run: mvn jacoco:report
 
       - name: Generate Jacoco Badge
         id: jacoco
+        if: inputs.run_unit_test
         uses: cicirello/jacoco-badge-generator@v2.0.1
       - name: Log coverage percentage
+        if: inputs.run_unit_test
         run: |
           echo "Coverage percentage: ${{ steps.jacoco.outputs.coverage }}"
           echo "branch coverage: ${{ steps.jacoco.outputs.branches }}"
 
       - name: Upload Jacoco coverage report
+        if: inputs.run_unit_test
         uses: actions/upload-artifact@v4
         with:
           name: jacoco-report
           path: target/site/jacoco/
 
       - name: Upload build artifacts for Sonar
+        if: inputs.run_build
         uses: actions/upload-artifact@v4
         with:
           name: build-artifacts
